services:
  dev:
    image: mcr.microsoft.com/devcontainers/base:ubuntu
    command: sleep infinity
    volumes:
      - ..:/workspace
      - ${HOME}/.claude:/home/vscode/.claude:ro
      - ${HOME}/.codex:/home/vscode/.codex:ro
      - ${HOME}/.config/git:/home/vscode/.config/git:ro
      - ${HOME}/.gitconfig:/home/vscode/.gitconfig:ro
      - ${HOME}/.zshrc:/home/vscode/.zshrc.host:ro
      - ./.zshrc:/home/vscode/.zshrc:ro
      - ./mise.container.toml:/workspace/.devcontainer/mise.toml:ro
      - ${HOME}/.bashrc:/home/vscode/.bashrc:ro
      - ${HOME}/.vimrc:/home/vscode/.vimrc:ro
    working_dir: /workspace
